### ISSUE TITLE
Undefined symbol exception using bsonsearch.bsoncompare

### ISSUE THREAD

**Issue by quimm2003** [bauman/bsonsearch#1]
Hi there,

I'm using debian jessie, I've installed dependencies, cloned the code and compiled the source code using this command:

> $ gcc -Wall -I/usr/local/include/libbson-1.0 -L/usr/local/lib -lbson-1.0  -DWITH_PROJECTION -DWITH_UTILS -DWITH_CONDITIONAL -DWITH_TEXT -DWITH_STEMMER -DWITH_ASPELL -DWITH_YARA -lpcre -shared -o libbsoncompare.so -fPIC bsoncompare.c mongoc-matcher.c mongoc-matcher-op.c mongoc-matcher-op-geojson.c mongoc-bson-descendants.c

Installed libbsoncompare.so:

> cp libbsoncompare.so /usr/lib
> ldconfig -n /usr/lib

And when I try to use it in python code:

> from bsonstream import KeyValueBSONInput
> import bsonsearch
> with bsonsearch.bsoncompare() as bc:

I always get an exception which is thrown at bsonsearch/\__init__.py, line 40: 

> OSError: /usr/lib/libbsoncompare.so: undefined symbol: _mongoc_matcher_op_yara_new

Am I missing something?

Thanks

**Comment by bauman** [comment]
if you are going to include yara support `(-DWITH_YARA)`, you need to link against yara at compile time by adding `-lyara` in the gcc line

the RedHat spec file has two versions baked in, one with everything and a "lite" version with only the basics. 

https://github.com/bauman/bsonsearch/blob/master/lib/bsoncompare.spec#L95-L96

Start by copying the lite version and include other functions as you see fit.
